version: "3.9"
services:
  postgresqldb:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  c2-server:
    env_file:
      - production.env
    image: "c2-server:latest"
    build: "../"
    command: [ "c2-server" ]
    ports:
      - "9001:9001"
    depends_on:
      - postgresqldb
    restart: always
  c2-frontend:
    image: "web-app:latest"
    build: "../c2-frontend/"
    command: [ "nginx", "-g", "daemon off;" ]
    ports:
      - "80:80"
    depends_on:
      - postgresqldb
      - c2-frontend
    restart: always
